# Generated by Django 2.2 on 2020-07-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200722_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=300, verbose_name='Статус'),
        ),
    ]
