# Generated by Django 2.2 on 2020-07-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200722_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='completion_time',
            field=models.DateField(blank=True, null=True, verbose_name='Время выполнения'),
        ),
    ]
