# Generated by Django 2.2 on 2020-07-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200722_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='completion_time',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Время выполнения'),
        ),
    ]
