# Generated by Django 2.2 on 2020-07-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200723_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do_list',
            name='summary',
            field=models.CharField(default='None description', max_length=300, verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='to_do_list',
            name='description',
            field=models.TextField(blank=True, default='None description', max_length=3500, null=True, verbose_name='Описание'),
        ),
    ]
